import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";

const mono = JetBrains_Mono({
  subsets: ['latin']
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${mono.className} min-h-screen flex flex-col`} >
          <main className="flex-1 flex flex-col">
              {children}
            </main> 
        </body>
      </html>
    </ClerkProvider>
  );
}
